---
- name: Install package and starts the service
  hosts: node1
  tasks:
    - name: Install the required package
      yum:
        name: "{{ansible_facts.ansible_local.custom.general.package}}"
        state: latest

    - name: Start the service
      service:
        name: "{{ansible_facts.ansible_local.custom.general.package}}"
        state: "{{ansible_facts.ansible_local.custom.general.state}}"
