---
- name: use jinja2 template
  hosts: all
  vars:
    system_owner: xjf@xjf.com
  tasks:
    - name: use templete module
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0640

...
